spring:
  application:
    name: gateway-zuul
  redis:
    host: localhost
    port: 6379
    password: 123321
server:
  port: 8910
zuul:
  routes:
    #    api-a:
    #      path: /simplereoute/**
    #      url: http://www.baidu.com
    #    orderservice:
    #      path: /orderservice/**
    #      serviceId:  order-service
    order-service: /orderservice/**

  ratelimit:
    enabled: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
    policy-list:
      orderservice:
        - limit: 2 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - URL=/order/

    #      - type:
    #          URL=/order/ping
    #          - URL=/order/ping
    #          - user
    #          - origin
    #          - httpmethod
    #     - type:
    #          - url=/all
    repository: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka-server.ip@:@eureka-server.port@/eureka/

