spring:
  application:
    name: product-service
server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka-server.ip@:@eureka-server.port@/eureka/
