spring:
  application:
    name: order-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://@zipkin-server.ip@:@zipkin-server.port@
server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka-server.ip@:@eureka-server.port@/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"