spring:
  application:
    name: order-service
server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka-server.ip@:@eureka-server.port@/eureka/
feign:
  hystrix:
    enabled: true