server:
  port: @eureka-server.port@
eureka:
  instance:
    hostname: @eureka-server.ip@
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/